config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charts do
    resources :songs
  end
  resources :artists do
    resources :songs
  end
  resources :playlists do
    resources :songs 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy
end

app/models/chart.rb
class Chart < ApplicationRecord
    has_many :songs, dependent: :destroy
    has_many :artists, through: :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :chart, optional: true
  belongs_to :playlist, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :playlists
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :password, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to artists_path
    else
      render :new
    end

  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def artist_params
      params.require(:artist).permit(:name, :picture)
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :update, :edit, :destroy]
  def index
    @charts = Chart.all
  end

  def show
  end

  def new
    @chart = Chart.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @chart = Chart.new(chart_params)

    if @chart.save
      redirect_to charts_path
    else
      render :new
    end

  end

  def update
    if @chart.update(chart_params)
      redirect_to @chart
    else
      render :edit
    end
  end

  def destroy
    @chart.destroy
    redirect_to charts_path
  end

  private
    def chart_params
      params.require(:chart).permit(:genre)
    end

    def set_chart
      @chart = Chart.find(params[:id])
    end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :update, :edit, :destroy]

  def index
    @playlists = current_user.playlists
  end

  def show
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = current_user.playlists.new(playlist_params)
    if @playlist.save
      redirect_to playlists_path
    else
      render :new
    end
      
  end

  def edit

  end

  def update
    if @playlist.update(playlist_params)
      redirect_to playlists_path
    else
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    redirect_to playlists_path
  end

  private

    def playlist_params
      params.require(:playlist).permit(:name)
    end

    def set_playlist
      @playlist = current_user.playlists.find(params[:id])
    end

  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :update, :edit, :destroy]

  def new
    @song = Song.new
    render partial: 'form'
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      # redirect_to artist_song_path(@song.artist_id, @song)
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end
  
  def update
    if @song.update(song_params)
      redirect_to artists_path
    else 
      render :new
    end
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end
  
    def song_params
      params.require(:song).permit(:title, :genre, :length, :chart_id, :playlist_id)
    end

    def set_song
      @song = Song.find(params[:id])
    end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
    def generate_song_lengths
        first_digits = ["2", "3", "4"]
        second_digits = ["0", "1", "2", "3", "4", "5"]
        third_digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
        return first_digits.sample + ":" + second_digits.sample + third_digits.sample
    end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: @artist, local: true, class: "ui form") do |f|%>
    <div class="field">
        <%= f.label :name  %>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :picture  %>
        <%= f.text_field :picture %>
    </div>

    <%= f.submit %>
<% end %>
<%= link_to 'Back to Artists', artists_path %>

app/views/artists/index.html.erb
<div class="container">

</div>
<h1 class="ui header centered">List of all Artists</h1>
<hr>
<div class="artist-view-container">
    <% @artists.each do |artist|%>
        <div class="ui card">
            <h2 class="ui header centered" style="margin-top: 5px; margin-bottom: 5px;">
                <%= artist.name %>
            </h2>
            <img class="ui image" src="https://robohash.org/<%= artist.picture %>?set=set2" />
            <hr style="width: 100%">
            <%  artist.songs.each do |song| %>
                <ul id="song-list">
                    <li><%= render 'songs/song', { song: song } %></li>
                    <li> <%= link_to 'Edit Song', edit_artist_song_path(artist, song)%>
                </ul>
            <% end %>
            <div class="ui buttons">
                <button class="button"><%= link_to 'Add a song', new_artist_song_path(artist) %></button>
                <button class="button"><%= link_to 'Edit Artist', edit_artist_path(artist) %></button>
                <button class="button"><%= link_to 'Remove Artist', artist_path(artist), method: :delete %></button>
            </div>
        </div>
    <% end %>

</div>
<div class="extra content">
    <p class="header right">
        <%= link_to 'New artist', new_artist_path %>
    </p>
    <p class="header right">
        <%= link_to 'Back', root_path %>
    </p>
</div>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<div class="ui card">
    <div class="content">
        <p class="header">
                <%= @artist.name %>
        </p>
        <img class="ui image" src="https://robohash.org/<%= @artist.picture %>?set=set2" />
        <% @artist.songs.each do |song| %>
            <%= render 'songs/song', { song: song } %>
        <% end %>
    </div>
        


    <div class="extra content">
        <%= link_to 'Add a song', new_artist_song_path(@artist) %>
        <%= link_to 'Back', artists_path %>
        <%= link_to 'Edit Artist', edit_artist_path(@artist) %>
        <%= link_to 'Remove Artist', artist_path(@artist), method: :delete %>
    </div>

</div>

app/views/charts/_form.html.erb
<h1 class="ui header">Add a Chart</h1>
<%= form_with(model: @chart, local: true, class: "ui form") do |f| %>
    <div class="field">
        <%= f.label :genre, "Name of Chart" %>
        <%= f.text_field :genre, required: true %>
    </div>

    <%= f.submit  %>
<% end %>
<%= link_to 'Back to All', charts_path %>

app/views/charts/index.html.erb
<h1 class="ui header centered">List of all Charts</h1>
<hr />
    <div style="display: flex; justify-content: space-evenly;">
        <% @charts.each do |chart|%>
            <div class="ui card">
                <h2 class="ui header centered">
                    <%= chart.genre %>
                </h2>

                <% chart.songs.shuffle.each_with_index do |song, index| %>
                    <%= "##{index + 1} #{song.title} - #{song.artist.name}" %>
                <br/>
                <% end %>
                
                <%= link_to 'Edit', edit_chart_path(chart) %>
                <%= link_to 'Remove', chart_path(chart), method: :delete %>
            </div>
        <% end %>
    </div>
<div>
    <%= link_to 'New Chart', new_chart_path %>
    <%= link_to 'Back', root_path %>
</div>

app/views/charts/new.html.erb
<h1>Charts#new</h1>
<p>Find me in app/views/charts/new.html.erb</p>

app/views/charts/show.html.erb
<div class="ui card">
    <h1><%= @chart.genre %></h1>

    <% @chart.songs.shuffle.each_with_index do |song, index| %>
        <%= "##{index + 1} #{song.title} - #{song.artist.name}" %>
        <br/>
    <% end %>
    
    <%= link_to 'Edit', edit_chart_path %>
    <%= link_to 'Remove', chart_path, method: :delete %>
    <%= link_to 'Back to All', charts_path %>


</div>

app/views/layouts/_banner.html.erb
<div id="banner">
    <%= image_tag 'BillboardLogo2013.svg.png' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="ui container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= render partial: 'layouts/banner' %>
      <%= yield %>
    </div>
  </body>
</html>
      

app/views/playlists/edit.html.erb
<h1>Edit playlist</h1>
<%= form_with(model: @playlist, local: true, class: "form") do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <%= f.submit %>
<% end %>

app/views/playlists/index.html.erb
<h2>Welcome <%= current_user.username %></h2>
<hr />
<%= link_to "Add Playlist", new_playlist_path %>
<h3>Your Playlists</h3>
<ul>
  <% @playlists.each do |playlist| %>
    <li>
      <%= playlist.name %> 
      <%= link_to 'View Playlist', playlist_path(playlist) %>
    </li>
  <% end %>
</ul>

app/views/playlists/new.html.erb
<h1>Add playlist</h1>
<%= form_with(model: @playlist, local: true, class: "form") do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <%= f.submit %>
<% end %>

app/views/playlists/show.html.erb
<% @playlist.songs.each do |song|%>
    <li><%= song.title %></li>
<% end %>
<%= link_to 'Edit Playlist', edit_playlist_path(@playlist) %>
<%= link_to 'Remove Playlist', playlist_path(@playlist), method: :delete %>

app/views/songs/_form.html.erb
<h1>Add a song</h1>

<%= form_with(model: [@artist, @song], local: true, class: "ui form" ) do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :genre %>
        <%= f.text_field :genre %>
    </div>

    <div class="field">
        <%= f.label :length %>
        <%= f.number_field :length, step: 0.01 %>
    </div>

    <div class="field">
        <%= f.label :chart_id, "Select a chart" %>
        <%= f.select  :chart_id, options_for_select([['none', nil], ['Top 100 US', 9], ['Top 100 Euro', 10], ['Hot 100', 11]]) %>
    </div>

    <div class="field">
        <%= f.label :playlist_id, "Add to Your Playlist" %>
        <%= f.collection_select :playlist_id, current_user.playlists, :id, :name, :prompt => true %>
    </div>
    <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/songs/_song.html.erb
<p>
    <%= song.title %> - (<%= generate_song_lengths %>) (<%= song.genre %>)
</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>

app/views/static_pages/home.html.erb
<hr/>
<h1 class="ui header centered"><%= link_to 'All Artists', artists_path %></h1>
<hr/>
<h1 class="ui header centered"><%= link_to 'All Charts', charts_path %></h1>
<hr/>
<h1 class="ui header centered"><%= link_to 'Your Playlists', playlists_path %></h1>
<hr />
<%= button_to 'Log Out', destroy_user_session_path, method: :delete %>